name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g bower
    - run: mkdir dist; cp *.html dist; cp *.css dist; cp *.js dist; cp *.png dist; cp bower.json dist
    - run: cd dist; bower install -p
    
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: dist
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}

